### ISSUE TITLE
Overlapping sticky sidebar

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-FixedHeader#1]
The header overlaps the sticky sidebar.

I can't think of an optimal solution... if you add the following css, it doesn't overlap but it jumps down and end up overlapping the page footer in some cases (when using ZenHub which adds extra sections to the sidebar).

``` css
.discussion-sidebar.is-stuck {
  margin-top: 50px !important;
}
```
