### ISSUE TITLE
Fixed header overlapping when opening links for code specific lines

### ISSUE THREAD

**Issue by jetersen** [StylishThemes/GitHub-FixedHeader#9]
The header has starting overlapping code changes when opening links.
https://github.com/casz/fastlane/blob/9b7ebab16ebbace1178fc6f6d1f1b232372e5419/fastlane/lib/fastlane/actions/set_info_plist_map.rb#L12-L15

With fixed header on
![image](https://user-images.githubusercontent.com/1661688/31255735-a34b66d4-aa2e-11e7-8aa3-5cce2e4889e4.png)

With fixed header off
![image](https://user-images.githubusercontent.com/1661688/31255754-be112b8e-aa2e-11e7-9d68-eb84c4e969c7.png)

Don't recall it being a issue, hence this issue was created.

**Comment by Mottie** [comment]
Hi @casz!

Please make sure you have v1.1.15 of the style installed. The current version doesn't have this issue, so I would have to guess you might still be using Stylish because it hasn't been updating styles properly. I would recommend you switch to [Stylus](http://add0n.com/stylus.html).

**Comment by jetersen** [comment]
Before reporting I verified it was updated, already using Stylus
```
/*! Github Fixed Header Theme v1.1.15 (9/2/2017) *//*
 * https://github.com/StylishThemes/GitHub-FixedHeader
 * https://userstyles.org/styles/124438
 * License: https://creativecommons.org/licenses/by-sa/4.0/
 */
```

```
Google Chrome is up to date
Version 61.0.3163.100 (Official Build) (64-bit)
```

**Comment by jetersen** [comment]
Perhaps it's combination of refined github and fixed header?

**Comment by Mottie** [comment]
Oh wait, you're right... I misunderstood you. I'll have to take a closer look later tonight.

**Comment by jetersen** [comment]
Updated screenshots to show it better 👍 

Must be a change Github made, I recall they opened all links with few lines above the specific code line that was referenced on the link.

**Comment by Mottie** [comment]
Hmm, well it looks like GitHub looks for at the hash `#L12-L15`, then looks for the table cell that has an id of "LC12" (in this case) and then uses [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to set the top. 

```html
<tr>
  <td id="L12" class="blob-num js-line-number" data-line-number="12"></td>
  <td id="LC12" class="blob-code blob-code-inner js-file-line highlighted">...</td>
</tr>
```

I've tried various (CSS only) methods to get it to move, but nothing is working so far 😿

* Reposition code cell pseudo element

    ```css
    .blob-code-inner:after {
      content: " ";
      position: absolute !important;
      top: -60px !important;
      left: 0 !important;
      pointer-events: none;
    }
    ```

* Tweak code cell pseudo element (moves copy button up)

    ```css
    .blob-code-inner:after {
      content: " ";
      position: absolute !important;
      padding-top: 60px !important;
      margin-top: -60px !important;
      pointer-events: none;
    }
    ```

* Last resort: tweak line numbers

    ```css
    .blob-num:after {
      content: " ";
      display: inline-block !important;
      position: relative !important;
      padding-top: 60px !important;
      margin-top: -60px !important;
      width: 1px !important;
    }
    ```

I think this one is going to require a javascript solution; otherwise I'm out of ideas. Any thoughts @silverwind?
